/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_system;

import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author SAIMIHIRNATH
 */
public class NewBook extends javax.swing.JFrame {

    /**
     * Creates new form NewBook
     */
    public NewBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookInformation = new javax.swing.JLabel();
        BookID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Publisher = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        PublishedYear = new javax.swing.JLabel();
        Capacity = new javax.swing.JLabel();
        BookIDValue = new javax.swing.JTextField();
        NameValue = new javax.swing.JTextField();
        PublisherValue = new javax.swing.JTextField();
        PriceValue = new javax.swing.JTextField();
        PublishedYearValue = new javax.swing.JTextField();
        CapacityValue = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BookInformation.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        BookInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookInformation.setText("BOOK INFORMATION");
        getContentPane().add(BookInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 6, 500, 68));

        BookID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BookID.setText("Book ID");
        getContentPane().add(BookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 92, 170, 31));

        Name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name.setText("Name");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 141, 170, 30));

        Publisher.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Publisher.setText("Publisher");
        getContentPane().add(Publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 189, 170, 31));

        Price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Price.setText("Price");
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 238, 170, 31));

        PublishedYear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PublishedYear.setText("Published Year");
        getContentPane().add(PublishedYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 287, 170, 31));

        Capacity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Capacity.setText("Capacity");
        getContentPane().add(Capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 336, 170, 31));

        BookIDValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(BookIDValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 92, 334, -1));

        NameValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(NameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 141, 334, 30));

        PublisherValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(PublisherValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 189, 334, -1));

        PriceValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(PriceValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 238, 334, -1));

        PublishedYearValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(PublishedYearValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 287, 334, -1));

        CapacityValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(CapacityValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 336, 334, -1));

        Save.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/save-icon--1.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 412, 115, 43));

        Close.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/red-x-mark-transparent-background-3.png"))); // NOI18N
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 412, 120, 43));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/addbook.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String bookid=BookIDValue.getText();
        String name=NameValue.getText();
        String publisher=PublisherValue.getText();
        String price=PriceValue.getText();
        String publishedyear=PublishedYearValue.getText();
        String capacity=CapacityValue.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement st=con.prepareStatement("INSERT INTO BOOK VALUES(?,?,?,?,?,?)");
            st.setString(1,bookid);
            st.setString(2,name);
            st.setString(3,publisher);
            st.setString(4, price);
            st.setString(5,publishedyear);
            st.setString(6,capacity);
            int j=st.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully Updated.");
            setVisible(false);
            new NewBook().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookID;
    private javax.swing.JTextField BookIDValue;
    private javax.swing.JLabel BookInformation;
    private javax.swing.JLabel Capacity;
    private javax.swing.JTextField CapacityValue;
    private javax.swing.JButton Close;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameValue;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField PriceValue;
    private javax.swing.JLabel PublishedYear;
    private javax.swing.JTextField PublishedYearValue;
    private javax.swing.JLabel Publisher;
    private javax.swing.JTextField PublisherValue;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
