/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_system;

import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author SAIMIHIRNATH
 */
public class NewStudent extends javax.swing.JFrame {

    /**
     * Creates new form NewStudent
     */
    public NewStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        StudentRegistrationDetails = new javax.swing.JLabel();
        StudentID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        FatherName = new javax.swing.JLabel();
        MotherName = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        StudentMobileNumber = new javax.swing.JLabel();
        BranchName = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        StudentIDValue = new javax.swing.JTextField();
        NameValue = new javax.swing.JTextField();
        FatherNameValue = new javax.swing.JTextField();
        MotherNameValue = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        StudentMobileNumberValue = new javax.swing.JTextField();
        AddressValue = new javax.swing.JTextField();
        BranchNameValue = new javax.swing.JComboBox<>();
        PasswordValue = new javax.swing.JPasswordField();
        Save = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentRegistrationDetails.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        StudentRegistrationDetails.setForeground(new java.awt.Color(255, 255, 255));
        StudentRegistrationDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentRegistrationDetails.setText("STUDENT REGISTRATION DETAILS");
        getContentPane().add(StudentRegistrationDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 14, 616, 40));

        StudentID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StudentID.setForeground(new java.awt.Color(255, 255, 255));
        StudentID.setText("Student ID");
        getContentPane().add(StudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 83, 221, -1));

        Name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 129, 221, 30));

        FatherName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FatherName.setForeground(new java.awt.Color(255, 255, 255));
        FatherName.setText("Father Name");
        getContentPane().add(FatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 178, 221, 30));

        MotherName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MotherName.setForeground(new java.awt.Color(255, 255, 255));
        MotherName.setText("Mother Name");
        getContentPane().add(MotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 227, 221, 30));

        Gender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Gender.setForeground(new java.awt.Color(255, 255, 255));
        Gender.setText("Gender");
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 276, 221, 30));

        StudentMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StudentMobileNumber.setForeground(new java.awt.Color(255, 255, 255));
        StudentMobileNumber.setText("Student Mobile Number");
        getContentPane().add(StudentMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 325, 221, 30));

        BranchName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BranchName.setForeground(new java.awt.Color(255, 255, 255));
        BranchName.setText("Branch Name");
        getContentPane().add(BranchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 374, 221, 30));

        Address.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setText("Address");
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 423, 221, 30));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 473, 221, 29));

        StudentIDValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(StudentIDValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 80, 336, -1));

        NameValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameValueActionPerformed(evt);
            }
        });
        getContentPane().add(NameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 129, 336, -1));

        FatherNameValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(FatherNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 178, 336, -1));

        MotherNameValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(MotherNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 227, 336, -1));

        buttonGroup1.add(Male);
        Male.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Male.setForeground(new java.awt.Color(255, 255, 255));
        Male.setText("Male");
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 277, 123, -1));

        buttonGroup1.add(Female);
        Female.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Female.setForeground(new java.awt.Color(255, 255, 255));
        Female.setText("Female");
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 277, 98, -1));

        StudentMobileNumberValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(StudentMobileNumberValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 325, 336, -1));

        AddressValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(AddressValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 423, 336, -1));

        BranchNameValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BranchNameValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AERO", "BIO", "CCE", "CHEM", "CIVIL", "CSE", "DSE", "ECE", "EEE", "IPE", "IT", "MECH" }));
        getContentPane().add(BranchNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 374, 336, -1));

        PasswordValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(PasswordValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 472, 336, -1));

        Save.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/save-icon--1.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 535, 120, -1));

        Close.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/red-x-mark-transparent-background-3.png"))); // NOI18N
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 535, 120, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/50b.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameValueActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String studentid=StudentIDValue.getText();
        String name=NameValue.getText();
        String fname=FatherNameValue.getText();
        String mname=MotherNameValue.getText();
        String mobilenumber=StudentMobileNumberValue.getText();
        String address=AddressValue.getText();
        String gender="-";
        if(Male.isSelected())
        {
            gender="M";
        }
        else if(Female.isSelected())
        {
            gender="F";
        }
        String branchname=(String)BranchNameValue.getSelectedItem();
        String password=PasswordValue.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement st=con.prepareStatement("INSERT INTO STUDENT VALUES(?,?,?,?,?,?,?,?)");
            st.setString(1,studentid);
            st.setString(2,name);
            st.setString(3,fname);
            st.setString(4,mname);
            st.setString(5,gender);
            st.setString(6,mobilenumber);
            st.setString(7,branchname);
            st.setString(8,address);
            int i=st.executeUpdate();
            PreparedStatement pt=con.prepareStatement("INSERT INTO STUDENT_CREDENTIALS VALUES(?,?)");
            pt.setString(1, studentid);
            pt.setString(2,password);
            int j=pt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully Updated.");
            setVisible(false);
            new NewStudent().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AddressValue;
    private javax.swing.JLabel BranchName;
    private javax.swing.JComboBox<String> BranchNameValue;
    private javax.swing.JButton Close;
    private javax.swing.JLabel FatherName;
    private javax.swing.JTextField FatherNameValue;
    private javax.swing.JRadioButton Female;
    private javax.swing.JLabel Gender;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel MotherName;
    private javax.swing.JTextField MotherNameValue;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameValue;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordValue;
    private javax.swing.JButton Save;
    private javax.swing.JLabel StudentID;
    private javax.swing.JTextField StudentIDValue;
    private javax.swing.JLabel StudentMobileNumber;
    private javax.swing.JTextField StudentMobileNumberValue;
    private javax.swing.JLabel StudentRegistrationDetails;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel11;
    // End of variables declaration//GEN-END:variables
}
