/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrames;

/**
 *
 * @author SAIMIHIRNATH
 */
public class admin_home extends javax.swing.JFrame {

    /**
     * Creates new form admin_home
     */
    public admin_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageStudents = new javax.swing.JButton();
        ManageLibrarians = new javax.swing.JButton();
        ManageBooks = new javax.swing.JButton();
        Statistics = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageStudents.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        ManageStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newstudent.jpg"))); // NOI18N
        ManageStudents.setText("Manage Students");
        ManageStudents.setMaximumSize(new java.awt.Dimension(200, 75));
        ManageStudents.setMinimumSize(new java.awt.Dimension(200, 75));
        ManageStudents.setPreferredSize(new java.awt.Dimension(200, 75));
        ManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(ManageStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 105, 270, 110));

        ManageLibrarians.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        ManageLibrarians.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newlibrarian.png"))); // NOI18N
        ManageLibrarians.setText("Manage Librarians");
        ManageLibrarians.setMaximumSize(new java.awt.Dimension(100, 25));
        ManageLibrarians.setMinimumSize(new java.awt.Dimension(100, 25));
        ManageLibrarians.setPreferredSize(new java.awt.Dimension(200, 75));
        ManageLibrarians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageLibrariansActionPerformed(evt);
            }
        });
        getContentPane().add(ManageLibrarians, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 300, 110));

        ManageBooks.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        ManageBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newbook.png"))); // NOI18N
        ManageBooks.setText("Manage Books");
        ManageBooks.setMaximumSize(new java.awt.Dimension(100, 25));
        ManageBooks.setMinimumSize(new java.awt.Dimension(100, 25));
        ManageBooks.setPreferredSize(new java.awt.Dimension(200, 75));
        ManageBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageBooksActionPerformed(evt);
            }
        });
        getContentPane().add(ManageBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 270, 110));

        Statistics.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        Statistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/statistics.jpg"))); // NOI18N
        Statistics.setText("Statistics");
        Statistics.setMaximumSize(new java.awt.Dimension(100, 25));
        Statistics.setMinimumSize(new java.awt.Dimension(100, 25));
        Statistics.setPreferredSize(new java.awt.Dimension(200, 75));
        Statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticsActionPerformed(evt);
            }
        });
        getContentPane().add(Statistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 300, 110));

        Logout.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.jpg"))); // NOI18N
        Logout.setText("Logout");
        Logout.setMaximumSize(new java.awt.Dimension(100, 25));
        Logout.setMinimumSize(new java.awt.Dimension(100, 25));
        Logout.setPreferredSize(new java.awt.Dimension(200, 75));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 615, 270, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_home.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageStudentsActionPerformed
        // TODO add your handling code here:
        new ManageStudents().setVisible(true);
    }//GEN-LAST:event_ManageStudentsActionPerformed

    private void ManageLibrariansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageLibrariansActionPerformed
        // TODO add your handling code here:
        new ManageLibrarians().setVisible(true);
    }//GEN-LAST:event_ManageLibrariansActionPerformed

    private void ManageBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageBooksActionPerformed
        // TODO add your handling code here:
        new ManageBooks().setVisible(true);
    }//GEN-LAST:event_ManageBooksActionPerformed

    private void StatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticsActionPerformed
        // TODO add your handling code here:
        new Statistics().setVisible(true);
    }//GEN-LAST:event_StatisticsActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton ManageBooks;
    private javax.swing.JButton ManageLibrarians;
    private javax.swing.JButton ManageStudents;
    private javax.swing.JButton Statistics;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
