/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrames;

import java.util.*;
import Project.*;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.*;


/**
 *
 * @author yelam
 */
public class IssuedBooks extends javax.swing.JFrame {

    /**
     * Creates new form Student_View_Issued_Books
     */
    public IssuedBooks() {
        initComponents();
        clearTable();
        setIssuedBooksToTable();
    }
    
    public void clearTable(){
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookID", "IssuedDate", "DueDate", "ReturnedStatus", "Fine(Till Date)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowSelectionAllowed(false);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1520, 720));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 20, 148, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Issued Books");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 6, 390, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/v11-060622-pc-wallpaper-hd.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int calculatefine(String sid,String bid)
    {
        int days=0;
        int fine=0;
        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement st=con.prepareStatement("select returneddate,duedate from issue where studentid=? and bookid=?");
            st.setString(1,sid);
            st.setString(2,bid);
            ResultSet rs=st.executeQuery();
            String rd="";
            String dd="";
            while(rs.next())
            {
                rd=rs.getString(1);
                dd=rs.getString(2);
            }
            if(rd.matches("-"))
            {
                st=con.prepareStatement("select trunc(sysdate-to_date(?,?)) from dual");
                st.setString(1,dd);
                st.setString(2, "DD-MON-YYYY");
                rs=st.executeQuery();
            }
            else
            {
                st=con.prepareStatement("select trunc(to_date(?,?) - to_date(?,?)) from dual");
                st.setString(1,rd);
                st.setString(2, "DD-MON-YYYY");
                st.setString(3,dd);
                st.setString(4, "DD-MON-YYYY");
                rs=st.executeQuery();
            }
            while(rs.next())
            {
                days=Integer.valueOf(rs.getString(1));
            }
            if(days<=7)
            {
                fine=days;
            }
            else if(days>7&&days<=14)
            {
                fine = 7 + (days-7)*3;
            }
            else if(days>14)
            {
                fine = 7 + 7*3 + (days-14)*5;
            }
            if(fine<0)
            {
                fine=0;
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return fine;
    }
    
    public void setIssuedBooksToTable()
    {
        DefaultTableModel model;
        try{
            Connection con=ConnectionProvider.getCon();
            PreparedStatement st=con.prepareStatement("select studentid from login_log_student where log_id in (select max(log_id) from login_log_student)");
            ResultSet rs=st.executeQuery();
            String sid="";
            while(rs.next())
            {
                sid=rs.getString(1);
            }
            
            st = con.prepareStatement("select bookid,issueddate,duedate,returneddate from issue where studentid=?");
            st.setString(1,sid);
            rs = st.executeQuery();
            
            model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                String bookid = rs.getString(1);
                String issueddate = rs.getString(2);
                String duedate = rs.getString(3);
                String returneddate = rs.getString(4);
                String returnedstatus="YES";
                if(returneddate.matches("-"))
                {
                    returnedstatus="NO";
                }
                String fine=String.valueOf(calculatefine(sid,bookid));
                Object[] obj ={bookid,issueddate,duedate,returnedstatus,fine};
                model.addRow(obj);     
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssuedBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
