/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrames;

import Project.*;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author SAIMIHIRNATH
 */
public class librarian_login extends javax.swing.JFrame {

    /**
     * Creates new form librarian_login
     */
    public librarian_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserID = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        UserIDValue = new javax.swing.JTextField();
        PasswordValue = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserID.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        UserID.setForeground(new java.awt.Color(255, 255, 255));
        UserID.setText("USER ID");
        getContentPane().add(UserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 85, 44));

        Password.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("PASSWORD");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 109, 44));

        UserIDValue.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        getContentPane().add(UserIDValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 268, 44));

        PasswordValue.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        getContentPane().add(PasswordValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 268, 44));

        Login.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        Login.setText("LOGIN");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 95, 42));

        Close.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        Close.setText("CLOSE");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 510, 87, 42));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Shutterstock_1702429360-min.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, -270, 1920, 1350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_CloseActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        String userid=UserIDValue.getText();
        String password=PasswordValue.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement st=con.prepareStatement("select * from librarian_credentials where librarianid=?");
            st.setString(1,userid);
            ResultSet rs=st.executeQuery();
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(null,"User doesn't exist");
            }
            else
            {
                String correctHash=rs.getString(2);
                String salt=rs.getString(3);
                String enteredHash=Encryption.encrypt(password, salt);
                if(enteredHash.matches(correctHash))
                {
                    setVisible(false);
                    new librarian_home().setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Incorrect Password");
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(librarian_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(librarian_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(librarian_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(librarian_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new librarian_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordValue;
    private javax.swing.JLabel UserID;
    private javax.swing.JTextField UserIDValue;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
