/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrames;

/**
 *
 * @author SAIMIHIRNATH
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminLogin = new javax.swing.JButton();
        LibrarianLogin = new javax.swing.JButton();
        Studentlogin = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        Person = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminLogin.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        AdminLogin.setText("ADMIN LOGIN");
        AdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginActionPerformed(evt);
            }
        });
        getContentPane().add(AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 520, -1));

        LibrarianLogin.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        LibrarianLogin.setText("LIBRARIAN LOGIN");
        LibrarianLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrarianLoginActionPerformed(evt);
            }
        });
        getContentPane().add(LibrarianLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, 520, -1));

        Studentlogin.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        Studentlogin.setText("STUDENT LOGIN");
        Studentlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentloginActionPerformed(evt);
            }
        });
        getContentPane().add(Studentlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 720, 520, -1));

        Close.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        Close.setText("CLOSE");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 790, 520, -1));

        Person.setBackground(new java.awt.Color(0, 0, 0));
        Person.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design.png"))); // NOI18N
        Person.setOpaque(true);
        getContentPane().add(Person, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 520, 530));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16692.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    private void AdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new admin_login().setVisible(true);
    }//GEN-LAST:event_AdminLoginActionPerformed

    private void LibrarianLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrarianLoginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new librarian_login().setVisible(true);
    }//GEN-LAST:event_LibrarianLoginActionPerformed

    private void StudentloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentloginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new student_login().setVisible(true);
    }//GEN-LAST:event_StudentloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLogin;
    private javax.swing.JButton Close;
    private javax.swing.JButton LibrarianLogin;
    private javax.swing.JLabel Person;
    private javax.swing.JButton Studentlogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
